image: ubuntu
version: php-appveyor-{build}
shallow_clone: true
install:
- sh: sudo apt-get update > /dev/null
- sh: sudo apt-get install make autoconf automake libtool libtool-bin m4 wget libc-bin gzip bzip2 bison g++ git+ -y > /dev/null

- sh: sudo chmod +x compile.sh install_musl.sh
- sh: sudo su -c "./install_musl.sh https://github.com/ScerIO/musl-cross-make/releases/download/v1.0 aarch64-linux-musl"
- sh: sudo su -c "./install_musl.sh https://github.com/ScerIO/musl-cross-make/releases/download/v1.0 x86_64-linux-musl"

build_script:
- sh: sudo su -c "./compile.sh -t android-aarch64 -x -s -j4 -f"
- sh: cd bin/php7/bin; zip -r ../../../php-aarch64.zip php php.ini  > /dev/null;cd ../../..
- sh: sudo rm -rf bin

- sh: sudo su -c "./compile.sh -t linux64 -l -j4 -c -f x86_64"
- sh: cd bin/php7/bin; zip -r ../../../php-linux-x86_64.zip php php.ini  > /dev/null;cd ../../..
- sh: sudo rm -rf bin
artifacts:
- path: '*php-*.zip'
- path: '*install*.log'